CREATE DATABASE BOOK_STORE;

USE BOOK_STORE;

CREATE TABLE BOOKS (
BOOK_ID  INT PRIMARY KEY ,
TITLE VARCHAR(100),
AUTHOR VARCHAR(100),
GENRE VARCHAR(150),
PUBLISHED_YEAR INT,
PRICE NUMERIC (10,2),
STOCK INT
);

CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT PRIMARY KEY,
NAME VARCHAR(100),
EMAIL VARCHAR(100),
PHONE INT,
CITY VARCHAR(150),
COUNTRY VARCHAR(200)
);

CREATE TABLE ORDERS (
ORDER_ID INT PRIMARY KEY,
CUSTOMER_ID INT ,
BOOK_ID INT,
ORDER_DATE DATE,
QUANTITY INT ,
TOTAL_AMOUNT NUMERIC (10,2),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

SELECT * FROM BOOKS;

SELECT * FROM CUSTOMERS;

SELECT * FROM ORDERS;

#>>>>>>>>>>SIMPLE QUERIES

#1)Retrieve all books in the "Fiction" genre

SELECT * FROM BOOKS 
WHERE GENRE='FICTION';

#2) Find books published after the year 1950

SELECT * FROM BOOKS
WHERE PUBLISHED_YEAR >1950;

#3) List all customers from the Canada

SELECT * FROM CUSTOMERS 
WHERE COUNTRY='CANADA';

#4) Show orders placed in November 2023

SELECT * FROM ORDERS
WHERE ORDER_DATE between '2023/11/01' AND '2023/11/30';

#5) Retrieve the total stock of books available

SELECT SUM(STOCK)AS 
TOTAL_STOCK
FROM BOOKS;

#6) Find the details of the most expensive book

SELECT * from books
order by price desc
limit 1;

#7) Show all customers who ordered more than 1 quantity of a book

SELECT * FROM ORDERS 
WHERE QUANTITY >=2;

#8) Retrieve all orders where the total amount exceeds $20

SELECT * FROM ORDERS 
WHERE TOTAL_AMOUNT >=20;

#9) List all genres available in the Books table

SELECT distinct GENRE FROM BOOKS;

#10) Find the book with the lowest stock

SELECT * FROM BOOKS 
ORDER BY STOCK ASC
LIMIT 1;

#11) Calculate the total revenue generated from all orders

SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS;

# >>>>>>>>>>>>>INTERMIDIATE QUERIES

#1) Find the average price of books in the "Fantasy" genre

SELECT AVG(PRICE) FROM BOOKS
WHERE GENRE='FANTASY';

#2) Show the top 3 most expensive books of 'Fantasy' Genre

SELECT * FROM BOOKS 
WHERE GENRE='FANTASY'
ORDER BY PRICE ASC 
LIMIT 3;

#3) Retrieve the total number of books sold for each genre

SELECT B.GENRE,SUM(O.QUANTITY) TOTAL_BOOKS_SOLD
FROM BOOKS B 
JOIN ORDERS O 
ON B.BOOK_ID=O.BOOK_ID
GROUP BY B.GENRE;

#4) Retrieve the total quantity of books sold by each author

SELECT B.AUTHOR,SUM(O.QUANTITY) TOTAL_BOOKS_SOLD
FROM BOOKS B 
JOIN ORDERS O 
ON B.BOOK_ID=O.BOOK_ID
GROUP BY B.AUTHOR;

#>>>>>>>  ADVANCE QUERIES

#1) List customers who have placed at least 2 orders

SELECT C.CUSTOMER_ID,C.NAME,COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS C
JOIN ORDERS O ON
C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.NAME
HAVING COUNT(O.ORDER_ID)>=1;

#2) Find the most frequently ordered book

SELECT B.BOOK_ID,B.TITLE , COUNT(O.ORDER_ID) MOST_ORDERED_BOOK
FROM BOOKS B
JOIN ORDERS O ON
B.BOOK_ID=O.BOOK_ID
GROUP BY B.BOOK_ID
ORDER BY MOST_ORDERED_BOOK DESC
LIMIT 1;

#3) List the cities where customers who spent over $30 are located

SELECT DISTINCT C.CITY,O.TOTAL_AMOUNT
FROM CUSTOMERS C 
JOIN ORDERS O ON 
C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE O.TOTAL_AMOUNT > 30;

#4) Find the customer who spent the most on orders

SELECT C.CUSTOMER_ID , C.NAME , SUM(O.TOTAL_AMOUNT) AS TOP_CUSTOMER
FROM CUSTOMERS C
JOIN ORDERS O ON
C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.NAME
ORDER BY TOP_CUSTOMER DESC
LIMIT 1;

#5) Calculate the stock remaining after fulfilling all orders

SELECT B.BOOK_ID,B.TITLE,B.STOCK,COALESCE(SUM(O.QUANTITY),0) AS ORDER_QUANTITY,
B.STOCK-COALESCE(SUM(O.QUANTITY),0) AS REMAINING_QUANTITY
FROM BOOKS B
LEFT JOIN ORDERS O ON
B.BOOK_ID=O.BOOK_ID
GROUP BY B.BOOK_ID,B.TITLE;

SELECT * 
FROM Books
WHERE Price=(SELECT MAX(Price) 
FROM Books);